-- Oracle / memo_app user で実行する想定
-- 既存の memos テーブルがある場合は、必要に応じて DROP してください。
-- DROP TABLE memos;

CREATE TABLE memos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR2(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

SELECT id, content, created_at, updated_at
FROM memos
ORDER BY id;
